export const SET_TOKEN = "MACHINE_TEST/LOGIN_RESPONSE/SET_TOKEN";
export const LOGIN_SUBMIT = "MACHINE_TEST/LOGIN_SCREEN/LOGIN_SUBMIT";
export const SET_LOGIN_ERROR = "MACHINE_TEST/LOGIN_SCREEN/SET_LOGIN_ERROR";
