export const FETCH_USERS = "MACHINE_TEST/HOME_SCREEN/FETCH_USERS";
export const SET_USERS = "MACHINE_TEST/HOME_SCREEN/SET_USERS";
export const ADD_NEW_USER = "MACHINE_TEST/HOME_SCREEN/ADD_NEW_USER";
export const FILTER_USER = "MACHINE_TEST/HOME_SCREEN/FILTER_USER";
export const SET_FILTERED_USER = "MACHINE_TEST/HOME_SCREEN/SET_FILTERED_USER";
